#!/usr/bin/env bash
# commentaire
while IFS=":" read -r USERNAME PASSWORD USER_ID GROUP_ID f7 HOME_DIRECTORY USER_ID_INFO
      do
    echo "The user $USERNAME is part of the $GROUP_ID gang, lives in $HOME_DIRECTORY and rides $f7. $USER_ID's place is protected by the passcode $PASSWORD, more info about the user here: $USER_ID_INFO"
    done < /etc/passwd
