#!/usr/bin/env bash
# commentaire
while IFS=: read -r USERNAME PASSWORD USER_ID GROUP_ID COMMAND/SHELL HOME_DIRECTORY f5
      do
    echo "The user $USERNAME is part of the $GROUP_ID gang, lives in $HOME_DIRECTORY and rides $COMMAND/SHELL. $USER_ID's place is protected by the passcode $PASSWORD, more info about the user here: f5"
    done < /etc/passwd
